steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/jingzhangjz-experiment/sequential-ci:$COMMIT_SHA",
        "-t",
        "gcr.io/jingzhangjz-experiment/sequential-ci:latest",
        "--cache-from",
        "gcr.io/ml-pipeline-dogfood/sequential-ci:latest",
        "${_CODE_PATH}/sequential",
      ]
    id: "BuildImages"
  - name: "python:3.6-slim"
    entrypoint: "/bin/sh"
    args: [
        "-c",
        "cd ${_CODE_PATH};
        pip3 install https://storage.cloud.google.com/jingzhangjz-kfp/kfp.tar.gz;
        python sequential.py --commit_id $COMMIT_SHA;
        cp sequential.py.zip /workspace/sequential.zip",
      ]
    id: "PackagePipeline"
  - name: "gcr.io/cloud-builders/gsutil"
    args:
      [
        "cp",
        "/workspace/sequential.zip",
        "gs://$REPO_NAME/$COMMIT_SHA/sequential.zip",
      ]
    id: "UploadPipeline"
    waitFor: ["PackagePipeline"]
  - name: gcr.io/ml-pipeline-dogfood/kfptool
    entrypoint: "/bin/sh"
    args: [
        "-c",
        '/builder/kubectl.bash;
        python3 -c "import kfp; client=kfp.Client(namespace=\"$_NAMESPACE\"); client.create_pipeline_version(pipeline_id=\"$_PIPELINE_ID\", name=\"$COMMIT_SHA\", repo_name=\"$REPO_NAME\", commit_sha=\"$COMMIT_SHA\", url=\"https://storage.googleapis.com/$REPO_NAME/$COMMIT_SHA/sequential.zip\")"',
      ]
    env:
      - "CLOUDSDK_COMPUTE_REGION=us-central1-a"
      - "CLOUDSDK_CONTAINER_CLUSTER=standard-cluster-3"
    id: "CreatePipelineVersion"
  - name: gcr.io/ml-pipeline-dogfood/kfptool
    entrypoint: "/bin/sh"
    args: [
        "-c",
        '/builder/kubectl.bash;
        python3 -c "import kfp; client=kfp.Client(namespace=\"$_NAMESPACE\"); exp = client.create_experiment(name=\"$_EXPERIMENT_NAME\"); client.run_pipeline(exp.id, \"$COMMIT_SHA\", \"/workspace/sequential.zip\")"',
      ]
    env:
      - "CLOUDSDK_COMPUTE_REGION=us-central1-a"
      - "CLOUDSDK_CONTAINER_CLUSTER=standard-cluster-3"
    id: "RunPipeline"

images:
  - "gcr.io/ml-pipeline-dogfood/sequential-ci:$COMMIT_SHA"
  - "gcr.io/ml-pipeline-dogfood/sequential-ci:latest"

substitutions:
  _CODE_PATH: /workspace/experiment/ci/hello-world
  _NAMESPACE: kubeflow
  _PIPELINE_ID: 3326a026-6037-4aeb-b800-644f997049b6
  _EXPERIMENT_NAME: helloworldcd
