steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/jingzhangjz-experiment/helloworld-ci:$COMMIT_SHA",
        "-t",
        "gcr.io/jingzhangjz-experiment/helloworld-ci:latest",
        "--cache-from",
        "gcr.io/jingzhangjz-experiment/helloworld-ci:latest",
        "${_CODE_PATH}/helloworld",
      ]
    id: "BuildImages"
  - name: "python:3.7-slim"
    entrypoint: "/bin/sh"
    args: [
        "-c",
        "cd ${_CODE_PATH};
        pip3 install cffi==1.12.3 --upgrade;
        pip3 install https://storage.googleapis.com/jingzhangjz-kfp/kfp-0.1.23.tar.gz;
        python pipeline.py --commit_id $COMMIT_SHA;
        cp pipeline.py.zip /workspace/pipeline.zip",
      ]
    id: "PackagePipeline"
  - name: "gcr.io/cloud-builders/gsutil"
    args:
      [
        "cp",
        "/workspace/pipeline.zip",
        "gs://jingzhangjz-kfp/$COMMIT_SHA/pipeline.zip",
      ]
    id: "UploadPipeline"
    waitFor: ["PackagePipeline"]
  - name: "gcr.io/jingzhangjz-experiment/ubuntu-curl"
    args: ["bash", "./curl.bash", "$COMMIT_SHA", "$_PIPELINE_ID"]
    id: "CreatePipelineVersionAndRun"
images:
  - "gcr.io/jingzhangjz-experiment/helloworld-ci:$COMMIT_SHA"
  - "gcr.io/jingzhangjz-experiment/helloworld-ci:latest"

substitutions:
  _CODE_PATH: /workspace/experiment/ci/hello-world
  _NAMESPACE: kubeflow
  _PIPELINE_ID: 82766fb8-c7fb-4793-b7eb-34384daf5bcc
  _EXPERIMENT_NAME: helloworldexp
