apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  annotations:
    pipelines.kubeflow.org/pipeline_spec:
      '{"description": "A pipeline with two sequential
      steps.", "inputs": [{"default": "gs://ml-pipeline-playground/shakespeare1.txt",
      "description": "", "name": "url", "type": ""}], "name": "Sequential pipeline"}'
  generateName: sequential-pipeline-
spec:
  arguments:
    parameters:
      - name: url
        value: gs://ml-pipeline-playground/shakespeare1.txt
  entrypoint: sequential-pipeline
  serviceAccountName: pipeline-runner
  templates:
    - container:
        args:
          - echo "$0"
          - "{{inputs.parameters.gcs-download-data}}"
        command:
          - sh
          - -c
        image: library/bash:4.4.23
      inputs:
        parameters:
          - name: gcs-download-data
      name: echo
      outputs:
        artifacts:
          - name: mlpipeline-ui-metadata
            optional: true
            path: /mlpipeline-ui-metadata.json
          - name: mlpipeline-metrics
            optional: true
            path: /mlpipeline-metrics.json
    - container:
        args:
          - gsutil cat $0 | tee $1
          - "{{inputs.parameters.url}}"
          - /tmp/results.txt
        command:
          - sh
          - -c
        image: google/cloud-sdk:216.0.0
      inputs:
        parameters:
          - name: url
      name: gcs-download
      outputs:
        artifacts:
          - name: mlpipeline-ui-metadata
            optional: true
            path: /mlpipeline-ui-metadata.json
          - name: mlpipeline-metrics
            optional: true
            path: /mlpipeline-metrics.json
        parameters:
          - name: gcs-download-data
            valueFrom:
              path: /tmp/results.txt
    - dag:
        tasks:
          - arguments:
              parameters:
                - name: gcs-download-data
                  value: "{{tasks.gcs-download.outputs.parameters.gcs-download-data}}"
            dependencies:
              - gcs-download
            name: echo
            template: echo
          - arguments:
              parameters:
                - name: url
                  value: "{{inputs.parameters.url}}"
            name: gcs-download
            template: gcs-download
      inputs:
        parameters:
          - name: url
      name: sequential-pipeline
