steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "${_GCR_PATH}/mnist_train:$COMMIT_SHA",
        "-t",
        "${_GCR_PATH}/mnist_train:latest",
        "${_CODE_PATH}/train",
        "-f",
        "${_CODE_PATH}/train/Dockerfile",
      ]
    id: "MnistBuildFirstImage"

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "${_GCR_PATH}/mnist_tensorboard:$COMMIT_SHA",
        "-t",
        "${_GCR_PATH}/mnist_tensorboard:latest",
        "${_CODE_PATH}/tensorboard",
        "-f",
        "${_CODE_PATH}/tensorboard/Dockerfile",
      ]
    id: "MnistBuildSecondImage"


  - name: "python:3.7-slim"
    entrypoint: "/bin/sh"
    args: [
        "-c",
        "cd ${_CODE_PATH};
        pip3 install cffi==1.12.3 --upgrade;
        pip3 install kfp==0.1.37;
        python pipeline.py --gcr_address ${_GCR_PATH};
        cp pipeline.py.zip /workspace/pipeline.zip",
      ]
    id: "MnistPackagePipeline"

  - name: "gcr.io/cloud-builders/gsutil"
    args:
      [
        "cp",
        "/workspace/pipeline.zip",
        "${_GS_BUCKET}/$COMMIT_SHA/pipeline.zip"
      ]
    id: "MnistUploadPipeline"
    waitFor: ["MnistPackagePipeline"]


  - name: "gcr.io/cloud-builders/kubectl"
    entrypoint: "/bin/sh"
    args: [
        "-c",
        "cd ${_CODE_PATH};
        apt-get update;
        apt-get install -y python3-pip;
        apt-get install -y libssl-dev libffi-dev;
        /builder/kubectl.bash;
        pip3 install kfp==0.1.37;
        pip3 install kubernetes;
        python3 create_pipeline_version_and_run.py 
        --bucket_name ${_GS_BUCKET}
        --commit_sha $COMMIT_SHA
        --pipeline_id ${_PIPELINE_ID}"
      ]
    env:
      - "CLOUDSDK_COMPUTE_ZONE=us-central1-a"
      - "CLOUDSDK_CONTAINER_CLUSTER=sample"
    id: "MnistCreatePipelineVersionAndRun"

images:
  - "${_GCR_PATH}/mnist_train:$COMMIT_SHA"
  - "${_GCR_PATH}/mnist_train:latest"
  - "${_GCR_PATH}/mnist_tensorboard:$COMMIT_SHA"
  - "${_GCR_PATH}/mnist_tensorboard:latest"

substitutions:
  _CODE_PATH: /workspace/samples/contrib/versioned-pipeline-ci-samples/mnist-ci-sample
  _NAMESPACE: kubeflow
  _GCR_PATH: gcr.io/alert-ability-264507
  _GS_BUCKET: gs://dldaisy-test-bucket
  _PIPELINE_ID: f6f8558a-6eec-4ef4-b343-a650473ee613

